// import './login.cy'
// import './sources.cy'
// import './display.cy'
// import './overview_dialogue.cy'
// import './dialogue.cy'
// import './dashboard.cy'
// import "./dashboard_conditional_style_1.cy"
// import "./dashboard_conditional_style_2.cy"
// import './journal.cy'